export const TextStyles = {
    balance_label: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.8,
        dropShadowBlur: 1,
        dropShadowDistance: 3,
        fill: "#fdc23f",
        fontFamily: "Arial Black",
        // fontFamily: "Calibri",
        // fontSize: 27.32,
        fontSize: 24,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),
    balance_value: new PIXI.TextStyle({
        fontFamily: "Roboto Condensed",
        fontSize: 20.48,
        fill: 0xffffff,
    }),

    mobile_bet_panel_top: new PIXI.TextStyle({
        fontFamily: "Roboto Condensed",
        fontSize: 35,
        fill: 0xffffff,
    }),

    mobile_bet_panel_max_bet: new PIXI.TextStyle({
        fontFamily: "Roboto Condensed",
        fontSize: 35,
        fill: 0xffffff,
    }),

    mobile_bet_panel_bet_value_button: new PIXI.TextStyle({
        fontFamily: "Roboto Condensed",
        fontSize: 38.5,
        fill: 0xffffff,
    }),

    mobile_bet_panel_bet_value_text: new PIXI.TextStyle({
        fontFamily: "Roboto Condensed",
        fontSize: 38.5,
        fill: 0xffffff,
    }),

    win_label: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.8,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: ["#ffd666", "#f78a32"],
        fontFamily: "calibri bold",
        fontSize: 38,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),

    win_value: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.8,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: ["#ffd666", "#f78a32"],
        fontFamily: "calibri bold",
        fontSize: 38,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),
    coin_value_label: new PIXI.TextStyle({
        fontFamily: "Roboto Condensed",
        fontSize: 18,
        fill: 0xffffff,
    }),

    autospin_main_label: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: ["#ffcd41", "#f78a32"],
        fontFamily: "calibri bold",
        fontSize: 27,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),

    autospin_numbers: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: "#ffce39",
        fontFamily: "calibri bold",
        fontSize: 45,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),

    autospin_more_label: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: "#fdecca",
        fontFamily: "calibri bold",
        fontSize: 18,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),

    autospin_number: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: "#ffce39",
        fontFamily: "calibri bold",
        fontSize: 27,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),

    autospin_toggle: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: "#fdecca",
        fontFamily: "calibri bold",
        fontSize: 17.5,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),

    settings_music: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: "#fdecca",
        fontFamily: "calibri bold",
        fontSize: 22,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),

    settings_history_header: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: ["#ffcd41", "#f78a32"],
        fontFamily: "calibri bold",
        fontSize: 21,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),

    bonus_win_detail: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: ["#ffcd41", "#f78a32"],
        fontFamily: "calibri bold",
        fontSize: 40,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),

    settings_history_value: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: "#fdecca",
        fontFamily: "calibri bold",
        fontSize: 17,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),

    settings_history_label: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: "#fdecca",
        fontFamily: "calibri",
        fontSize: 17,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),

    settings_sound: new PIXI.TextStyle({
        fontFamily: "Myriad Pro",
        fontSize: 22,
        fill: 0xf2c40a,
    }),

    settings_mute: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: "#fdecca",
        fontFamily: "calibri bold",
        fontSize: 22,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),
    settings_mute_on: new PIXI.TextStyle({
        fontFamily: "Myriad Pro Bold",
        fontSize: 18,
        fill: 0xa38613,
    }),
    settings_help: new PIXI.TextStyle({
        fontFamily: "Myriad Pro",
        dropShadow: true,
        dropShadowAlpha: 0.5,
        dropShadowAngle: 0.4,
        dropShadowBlur: -7,
        dropShadowColor: "#0b062d",
        dropShadowDistance: 2,
        fill: ["#ffc30a", "#ffe374", "#ffc30a"],
        fillGradientStops: [0.1, 0.6, 0.7],
        fontSize: 38,
        stroke: "#3a1603",
        strokeThickness: 4,
    }),

    help_page_title: new PIXI.TextStyle({
        fontFamily: "Myriad Pro Bold",
        fontSize: 23,
        fill: 0xf2c40a,
    }),

    help_rule: new PIXI.TextStyle({
        fontFamily: "Myriad Pro Bold",
        fontSize: 13,
        fill: 0xf2c40a,
        align: "center",
        wordWrap: true,
        wordWrapWidth: 485,
    }),

    help_page_numbers: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: "#fdecca",
        fontFamily: "calibri bold",
        fontSize: 35,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),

    help_page1: new PIXI.TextStyle({
        fontFamily: "Myriad Pro Bold",
        fontSize: 15,
        fill: 0xf2c40a,
        align: "center",
        wordWrap: true,
        wordWrapWidth: 485,
    }),

    help_page1_title: new PIXI.TextStyle({
        fontFamily: "Myriad Pro Bold",
        fontSize: 18,
        fill: 0xf2c40a,
    }),

    help_page1_avalanche: new PIXI.TextStyle({
        fontFamily: "Myriad Pro Bold",
        fontSize: 17,
        fill: 0xf2c40a,
        lineHeight: 53,
    }),

    help_page2: new PIXI.TextStyle({
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: "#fdecca",
        fontFamily: "calibri bold",
        fontSize: 18,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),

    help_page_rules: new PIXI.TextStyle({
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: "#fdecca",
        fontFamily: "calibri bold",
        fontSize: 22,
        lineHeight: 24,
        miterLimit: 0,
        stroke: "white",
        wordWrap: true,
        wordWrapWidth: 650,
    }),

    help_page4: new PIXI.TextStyle({
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: "#fdecca",
        fontFamily: "calibri bold",
        fontSize: 27,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),

    help_page2_symbols: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: ["#ffcd41", "#f78a32"],
        fontFamily: "calibri bold",
        fontSize: 19,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),

    help_page3_symbols: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: ["#ffcd41", "#f78a32"],
        fontFamily: "calibri bold",
        fontSize: 26,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),

    help_page4_symbols: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: ["#ffcd41", "#f78a32"],
        fontFamily: "calibri bold",
        fontSize: 27,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),

    paytable_streak: new PIXI.TextStyle({
        fontFamily: "ARIAL",
        fontStyle: "bold",
        fontSize: 20,
        fill: 0xf2c40a,
    }),

    paytable_amount: new PIXI.TextStyle({
        fontFamily: "ARIAL",
        fontStyle: "bold",
        fontSize: 20,
        fill: 0xffffff,
    }),

    menu_title: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.1,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: ["#ffcd41", "#f78a32"],
        fontFamily: "calibri bold",
        fontSize: 44.85,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),

    free_spins: new PIXI.TextStyle({
        dropShadow: true,
        dropShadowAngle: 0,
        dropShadowBlur: 5,
        dropShadowColor: "#0d1221",
        dropShadowDistance: 2,
        fill: [
            "#fbf035",
            "#facc24",
            "#fdf590",
            "#fdf590",
            "#fbf035",
            "#facc24",
        ],
        fillGradientStops: [0, 0.3, 0],
        fontFamily: "ofont",
        fontSize: 41,
        stroke: "#311b07",
        strokeThickness: 3,
    }),

    line_win: new PIXI.TextStyle({
        dropShadow: true,
        dropShadowAngle: 0,
        dropShadowBlur: 5,
        dropShadowColor: "#0d1221",
        dropShadowDistance: 2,
        fill: [
            "#fbf035",
            "#facc24",
            "#fdf590",
            "#fdf590",
            "#fbf035",
            "#facc24",
        ],
        fillGradientStops: [0, 0.3, 0],
        fontFamily: "ofont",
        fontSize: 60,
        stroke: "#311b07",
        strokeThickness: 3,
    }),
    line_win_total: new PIXI.TextStyle({
        dropShadow: true,
        dropShadowAngle: 0,
        dropShadowBlur: 5,
        dropShadowColor: "#0d1221",
        dropShadowDistance: 2,
        fill: [
            "#fbf035",
            "#facc24",
            "#fdf590",
            "#fdf590",
            "#fbf035",
            "#facc24",
        ],
        fillGradientStops: [0, 0.3, 0],
        fontFamily: "ofont",
        fontSize: 72,
        stroke: "#311b07",
        strokeThickness: 3,
    }),
    bet: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.8,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: ["#ffd666", "#f78a32"],
        fontFamily: "Arial Black",
        // fontSize: 49.68,
        fontSize: 28,

        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),
    coin_value_value: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 120.8,
        dropShadowBlur: 1,
        dropShadowDistance: 4,
        fill: ["#ffd666", "#f78a32"],
        fontFamily: "calibri bold",
        // fontSize: 49.68,
        fontSize: 40,
        miterLimit: 0,
        stroke: "white",
        wordWrapWidth: 0,
    }),
    error: new PIXI.TextStyle({
        fontSize: 31,
        fill: 0xf2c40a,
        fontFamily: "Myriad Pro Bold",
        align: "center",
        wordWrap: true,
        wordWrapWidth: 450,
    }),
    continue_title: new PIXI.TextStyle({
        fontSize: 60,
        fill: [0xffce42, 0xf78932],
        fontFamily: "calibri bold",
    }),
    continue_title_h2: new PIXI.TextStyle({
        fontSize: 35,
        fill: [0xffce42, 0xf78932],
        fontFamily: "calibri bold",
    }),
    continue_title_h3: new PIXI.TextStyle({
        fontSize: 21,
        fill: [0xffce42, 0xf78932],
        fontFamily: "Myriad Pro Bold",
    }),
    continue_text: new PIXI.TextStyle({
        fontSize: 18,
        fill: [0xfdecca],
        fontFamily: "Myriad Pro Bold",
        letterSpacing: 0,
    }),

    popUp: new PIXI.TextStyle({
        fill: ["white"],
        fontSize: 18,
        fontWeight: "bold",
    }),

    popUpText: new PIXI.TextStyle({
        fill: ["white"],
        wordWrap: true,
        wordWrapWidth: 190,
        fontSize: 17,
        fontWeight: "bold",
        align: "left",
    }),

    bigWinTextValue: new PIXI.TextStyle({
        align: "center",
        dropShadow: true,
        dropShadowAngle: 1.8,
        dropShadowBlur: 2,
        dropShadowColor: "#ff2f11",
        dropShadowDistance: 4,
        fill: [
            "#fd8929",
            "#fffb47",
            "#fdfda5",
            "#fffb47",
            "#fda533",
            "#fffb45",
            "#fdfda5",
            "#fff73b",
            "#fb972d",
        ],
        fillGradientStops: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
        fontFamily: "GermaniaOne-Regular",
        fontSize: 146,
        letterSpacing: 4,
        miterLimit: 0,
        stroke: "#ff4d1d",
        strokeThickness: 1,
        wordWrapWidth: 0,
    }),
};
